#CREATE TABLE ""."USUARIOS" (
#	"ID"	INTEGER,
#	"USERNAME"	TEXT NOT NULL UNIQUE,
#	"EMAIL"	TEXT,
#	"PASSWORD"	TEXT,
#	"CARD"	TEXT,
#	PRIMARY KEY("ID" AUTOINCREMENT)
#);

/* DELETE 'db_psc' database*/
DROP SCHEMA IF EXISTS db_psc;
/* DELETE USER 'sqp' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'localhost';

/* CREATE 'db_psc' DATABASE */
CREATE SCHEMA db_psc;
/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD '1234' */
CREATE USER IF NOT EXISTS 'spq'@'localhost' IDENTIFIED BY '1234';

GRANT ALL ON db_psc.* TO 'spq'@'localhost';
